### DISCUSSION TITLE
I'm having some trouble getting things to run in a Docker Container

### DISCUSSION THREAD

**Discussion by dylviz** [vendurehq/vendure#2240] [Q&A]
I've been trying different things for a couple of days and just not having any luck. I'm new to docker but I'm hoping for some general guidance on this. I run `yarn dev` and everything looks great. But when I run `docker compose up`, I get 3 containers (worker, server, database) but both the worker and the server error out. I'm using a postgres DB.

Here is the worker error:
```
Error: getaddrinfo ENOTFOUND database
2023-06-20 17:41:18     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
```

And here is the server error:
```
Error: getaddrinfo ENOTFOUND database
2023-06-20 17:41:06     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
2023-06-20 17:41:06   errno: -3008,
2023-06-20 17:41:06   code: 'ENOTFOUND',
2023-06-20 17:41:06   syscall: 'getaddrinfo',
2023-06-20 17:41:06   hostname: 'database'
2023-06-20 17:41:06 }
```

And in the CLI window, I get this:
```
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5432 -> 0.0.0.0:0: listen tcp 0.0.0.0:5432: bind: address already in use
```

I'm just using the default docker-compose file that was included:
```
version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["yarn", "start:server"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: marketplace
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start:worker"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: marketplace
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
```

Any explanation would be helpful. Thank you.
